# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post", "notes", "projects", "tutorials"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🤖"
    subtitle = "本人为湖南大学人工智能与机器人学院自动化大二在读生，欢迎来到我的博客。"
    avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
# Utterances: GitHub 登录评论，评论以 Issue 形式存到下面的仓库中
[comments]
    enabled  = true
    provider = "utterances"

    [comments.utterances]
        repo      = "CJY719HNU/CJY719HNU.github.io"
        issueTerm = "pathname"
        label     = "comment"
